### ISSUE TITLE
Branch main fails for Galactic

### ISSUE THREAD

**Issue by AlexGisi** [BehaviorTree/BehaviorTree.ROS2#17]
At the time of `70aa7c9`, `bt_service_node.hpp` fails to build for galactic due to line 267,

```
future_response_ = service_client_->async_send_request(request).share();
```

In galactic, `async_send_request()` returns a `shared_future`, so further calling `.share()` invokes an error ([reference](https://docs.ros2.org/galactic/api/rclcpp/classrclcpp_1_1Client.html)).

Removing the call to `.share()` resolved the error.

**Comment by facontidavide** [comment]
End of Life
