### ISSUE TITLE
BT Not Running / Failed When Running Inside Docker Container

### ISSUE THREAD

**Issue by mich1342** [BehaviorTree/BehaviorTree.ROS2#59]
Hi, 

I am trying to dockerized my behavior tree calling several ros2 actions server. The action servers are running inside another container. 

Everything works well if I run the behavior tree outside the docker. 

When running inside the docker, it keeps telling that the action server is unreachable and kills itself. When I tried to enter the docker container terminal, I could list all the action servers using the `ros2 action list` command.

Could it be caused by it needs some time to recognize / discover the action server? 

Thank you in advance

**Comment by facontidavide** [comment]
Hi,

I don't believe that this problem is **directly** related to this library. If you find the issue and it does indeed require a change in the library, let me know
